### ISSUE TITLE
Private repo

### ISSUE THREAD

**Issue by mramezani64** [MHaghighat98/Fibonacci#1]
@MHaghighat98 , Please make the repo private. Then we start coworking together here.

**Comment by MHaghighat98** [comment]
![Screenshot from 2020-05-26 13-52-39](https://user-images.githubusercontent.com/62746461/82933705-5928b580-9f58-11ea-8d48-d2fbaaf2e797.png)
It doesn't let me to to that.

**Comment by mramezani64** [comment]
Can you transfer ownership to me?

**Comment by mramezani64** [comment]
Is it private now on your side? There must be a "private" icon on the name of repo now.

**Comment by MHaghighat98** [comment]
I was trying to edit the commits but the there was an error saying that :
"the commits are not staged"
and I'm having trouble editing them.

now it is private but it doesn't show the project it says: "we are unable
to provide this service"

**Comment by MHaghighat98** [comment]
I don't think that the privacy works for me because i couldn't make it
private at first due to security reasons, so I think it's better to
transfer the ownership then I will try to make changes to the commits.

**Comment by mramezani64** [comment]
OK, to commit follow the steps below:

- First in a terminal run -> `git cola` (Note if git cola gives error it means you need to install it by `sudo apt install git-cola`)
- Then you need to stage the modified files by double clicking on the files (a green check means the file is staged)
- Then add a commit in the box up left of the window
- Then after closing the cola interface in the terminal run -> `git push origin <NAME OF THE PKG>`

**Comment by MHaghighat98** [comment]
thanks,
should I make a new repo?
because I cannot make any changes to the project now.

**Comment by mramezani64** [comment]
You are a collaborators of the project. You should be able to change the project. What do you mean you are not able to make changes on the project?

**Comment by mramezani64** [comment]
You may have to clone the pkg one more time in your catkin_ws since I've changed the address by moving the project one step back to Fibonacci repo directory. Let me know how it goes.
